# Generated by Django 3.1.4 on 2021-01-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='合肥速率供应链管理有限公司', max_length=64, verbose_name='公司名称')),
                ('bankname', models.CharField(default='中国银行肥东支行', max_length=64, verbose_name='开户行')),
                ('bankID', models.CharField(default='185758792231', max_length=64, unique=True, verbose_name='银行账号')),
                ('beginningbalances', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='期初余额')),
            ],
            options={
                'verbose_name': '基本信息',
                'verbose_name_plural': '公司基本信息',
            },
        ),
    ]
