# Generated by Django 3.1.4 on 2021-01-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20210117_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=20, verbose_name='科目类别')),
                ('subcode', models.CharField(max_length=20, unique=True, verbose_name='科目编码')),
                ('subdescription', models.CharField(max_length=128, verbose_name='科目说明')),
                ('substatus', models.BooleanField(default=True, verbose_name='是否启用')),
                ('needsummary', models.BooleanField(default=False, verbose_name='是否需要汇总')),
                ('level', models.SmallIntegerField(blank=True, max_length=2, null=True, verbose_name='层级')),
                ('category', models.SmallIntegerField(blank=True, max_length=2, null=True, verbose_name='账户种类')),
                ('parentcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='上级科目编码')),
            ],
            options={
                'verbose_name': '科目结构',
                'verbose_name_plural': '科目结构',
            },
        ),
        migrations.AlterField(
            model_name='accountingvouchers',
            name='voucherfile',
            field=models.FileField(blank=True, null=True, upload_to='F:\\Auto Test\\BillingSystem\\upload\\2021-01-18', verbose_name='附件'),
        ),
    ]
