# Generated by Django 3.1.4 on 2021-01-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20210118_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='种类ID')),
                ('des', models.CharField(max_length=32, verbose_name='描述')),
            ],
            options={
                'verbose_name': '账户种类',
                'verbose_name_plural': '账户种类',
            },
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='科目类别')),
                ('des', models.CharField(max_length=32, verbose_name='类别描述')),
            ],
            options={
                'verbose_name': '科目类别',
                'verbose_name_plural': '科目类别',
            },
        ),
        migrations.AlterField(
            model_name='subjects',
            name='level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Account.subjectcategory', verbose_name='账户种类'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Account.subjecttype', verbose_name='科目类别'),
        ),
    ]
