# Generated by Django 3.1.4 on 2021-01-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20210118_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='parentcode',
        ),
    ]
