# Generated by Django 3.1.4 on 2021-01-19 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_subjects_parentcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordtime', models.DateField(verbose_name='账目日期')),
                ('billtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记账时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('voucherno', models.CharField(max_length=15, unique=True, verbose_name='凭证号')),
                ('debittotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='借方总金额')),
                ('credittotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='贷方总金额')),
                ('biller', models.CharField(max_length=10, verbose_name='入账人')),
                ('voucherfile', models.FileField(blank=True, null=True, upload_to='F:\\Auto Test\\BillingSystem\\upload\\2021-01-19', verbose_name='附件')),
            ],
            options={
                'verbose_name': '账目基本信息',
                'verbose_name_plural': '账目基本信息',
            },
        ),
        migrations.AlterField(
            model_name='accountingvouchers',
            name='voucherfile',
            field=models.FileField(blank=True, null=True, upload_to='F:\\Auto Test\\BillingSystem\\upload\\2021-01-19', verbose_name='附件'),
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.CharField(max_length=128, verbose_name='摘要')),
                ('subcodeset', models.CharField(max_length=128, verbose_name='科目编码')),
                ('debitamount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='借方金额')),
                ('creditamount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='贷方金额')),
                ('voucherno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Account.accountbaseinfo', to_field='voucherno', verbose_name='凭证号')),
            ],
        ),
    ]
