# Generated by Django 3.1.4 on 2021-01-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_auto_20210119_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='voucherno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='VNO', to='Account.accountbaseinfo', to_field='voucherno', verbose_name='凭证号'),
        ),
    ]
