# Generated by Django 3.1.4 on 2021-02-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_auto_20210119_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='csubcode',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='现金段'),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='dsubcode',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='明细段'),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='fsubcode',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='一级科目'),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='ssubcode',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='二级科目'),
        ),
        migrations.AlterField(
            model_name='accountbaseinfo',
            name='voucherfile',
            field=models.FileField(blank=True, null=True, upload_to='E:\\billingSystem\\upload\\2021-02-01', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='accountingvouchers',
            name='voucherfile',
            field=models.FileField(blank=True, null=True, upload_to='E:\\billingSystem\\upload\\2021-02-01', verbose_name='附件'),
        ),
    ]
